### PR TITLE
Feature(performance): export ratings by cohort

### PR DESCRIPTION
**Pull request by RedJanvier**
#### What does this PR do?
Provide all ratings within a cohort and filter them by date
#### Description of Task to be completed?
- [x] Lists all ratings within a cohort: `/api/v1/cohort/:id`
- [x] Filter returned ratings by date (if provided): `/api/v1/cohort/:id/performance?from=Date&to=Date`
#### How should this be manually tested?
- Clone the repo or pull changes from the remote the go to `ft-export-cohort` branch
- Run `yarn install` then `yarn dev` to test all the features stated above.

### CODE REVIEW

**Review by mansurissa — APPROVED** [review]
LGTM, you also rebases ch-update-node-version I'm

**Comment by RedJanvier** [comment]
>LGTM, you also rebases ch-update-node-version I'm
@mansurissa 
This is because the task is not yet merged I don't know why!

**Comment by ceelogre** [comment]
> > LGTM, you also rebases ch-update-node-version I'm'
> 
> @mansurissa This is because the task is not yet merged I don't know why!

Task has been merged but I believe since you don't have any conflicts you've rebased.

**Review by ceelogre — COMMENTED** [review]
Could you please provide us with the endpoints to use while testing in the description?

**Comment by RedJanvier** [comment]
> > > LGTM, you also rebases ch-update-node-version I'm'
> > 
> > 
> > @mansurissa This is because the task is not yet merged I don't know why!
> 
> Task has been merged but I believe since you don't have any conflicts you've rebased.

Not yet rebased!

**Comment by RedJanvier** [comment]
> ?

I thought you were going to use the documentation (Swagger) but the endpoints are like those on trello. Check the updated PR Description @ceelogre

**Review by ceelogre — COMMENTED** [review]
I can access the first endpoint 
Capture d’écran 2021-09-29 à 11 14 00

but not the second

Capture d’écran 2021-09-29 à 11 12 56

**Comment by RedJanvier** [comment]
Sorry @ceelogre! For the second endpoint I think it is for manager only access token

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
